services:
  frontend:
    restart: always
    build: ./frontend
    ports:
      - '3000:3000'
    working_dir: /app
    volumes:
      - frontend_node_modules:/app/node_modules
      - ./frontend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - api
  api:
    restart: always
    build: ./api
    ports:
      - '5000:5000'
    working_dir: /app
    volumes:
      - ./api:/app

volumes:
  frontend_node_modules:
